<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Exercises : Cleaning and Combining Data With pandas Part 1: 
# Cleaning Data

---

In [2]:
import pandas as pd

In [3]:
# 6.1 Identifying Missing Data
# We will use the orders table from Super Store for these tasks
orders = pd.read_csv('./data/orders.csv')

orders.head(3)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0
2,ES-2018-853948,28/07/2018 00:00,29/07/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,77095.0,1488.0

In [4]:
# A. Start with some exploratory analysis methods to inspect the data
# Your code here please
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 990677 entries, 0 to 990676
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   order_id     990677 non-null  str
 1   order_date   990677 non-null  str
 2   ship_date    990677 non-null  str
 3   ship_mode    990677 non-null  str
 4   customer_id  990677 non-null  str
 5   product_id   990677 non-null  str
 6   sales        990677 non-null  float64
 7   quantity     990677 non-null  int64
 8   discount     990677 non-null  float64
 9   profit       990677 non-null  float64
 10  postal_code  191101 non-null  float64
 11  region_id    990484 non-null  float64
dtypes: float64(5), int64(1), str(6)
memory usage: 168.1 MB

In [82]:
# NO CODE HERE PLEASE

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990677 entries, 0 to 990676
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   order_id     990677 non-null  object
 1   order_date   990677 non-null  object
 2   ship_date    990677 non-null  object
 3   ship_mode    990677 non-null  object
 4   customer_id  990677 non-null  object
 5   product_id   990677 non-null  object
 6   sales        990677 non-null  float64
 7   quantity     990677 non-null  int64
 8   discount     990677 non-null  float64
 9   profit       990677 non-null  float64
 10  postal_code  191101 non-null  float64
 11  region_id    990484 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 90.7+ MB

In [10]:
# B. Which column has the most missing data? Sort the columns by sum of null values
# Your code here please
orders.isna().sum().sort_values(ascending=False)

postal_code    799576
region_id         193
order_id            0
order_date          0
ship_mode           0
ship_date           0
customer_id         0
product_id          0
quantity            0
sales               0
profit              0
discount            0
dtype: int64

In [7]:
# NO CODE HERE PLEASE

postal_code    799576
region_id         193
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
product_id          0
sales               0
quantity            0
discount            0
profit              0
dtype: int64

In [17]:
# C. Looks like postal_code is our biggest problem, along with region_id
# Use a combination of filtering, isnull, and sum to count how many rows are missing both columns
# Your code here please
mask = orders['postal_code'].isnull()
orders[mask]['region_id'].isnull().sum()

np.int64(193)

In [11]:
# NO CODE HERE PLEASE

193

In [25]:
# D. Let's drop the region_id nulls from the dataframe before proceeding
# Your code here please
orders=orders.dropna(subset=['region_id'])
orders.isnull().sum().sort_values(ascending=False)

postal_code    799383
order_id            0
ship_date           0
order_date          0
ship_mode           0
customer_id         0
sales               0
product_id          0
quantity            0
discount            0
profit              0
region_id           0
dtype: int64

In [14]:
# NO CODE HERE PLEASE

postal_code    799383
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
product_id          0
sales               0
quantity            0
discount            0
profit              0
region_id           0
dtype: int64

Our IT team confirmed that all missing postal code values should be 10001. Let's fill the null values using a built-in pandas function called `.fillna()`. This function will fill all the null values with a specified replacement, and it accepts the `inplace = True` statement to make our changes stick.

In [26]:
# E. It's the dream scenario! The IT team confirms all missing postal_code values should be 10001.0
# Your code here please
orders.fillna(value= 10001, inplace = True).isnull().sum()

order_id       0
order_date     0
ship_date      0
ship_mode      0
customer_id    0
product_id     0
sales          0
quantity       0
discount       0
profit         0
postal_code    0
region_id      0
dtype: int64

In [15]:
# NO CODE HERE PLEASE

order_id       0
order_date     0
ship_date      0
ship_mode      0
customer_id    0
product_id     0
sales          0
quantity       0
discount       0
profit         0
postal_code    0
region_id      0
dtype: int64

In [34]:
# 6.2 Cleaning Our Data
# A. Write a profit_margin function that accepts a row of data, which is a dictionary
#    It should return the result of dividing the profit column by the sales column (i.e. profit/sales)
def profit_margin(x) :
    return x['profit']/x['sales']

In [35]:
# B. Create a new column in the orders dataframe called 'profit_margin' by applying the profit margin function row-by-row
# Your code here please
orders['profit_margin']=orders.apply(profit_margin, axis=1)
orders.head(2)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0

In [17]:
# NO CODE HERE PLEASE

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0

We also want to create a column called `margin_categorization` that categorizes our new profit margin as "profitable", "unprofitable", or "break even". We can create a new function to do this, and then apply it to our orders DataFrame using the same method as above.

The function should follow these rules:
- If the profit_margin is greater than 0, the function should return "profitable"
- If the profit_margin is 0, the function should return "break even"
- If the profit_margin is less than 0, the function should return "unprofitable"

In [39]:
# C. Use the same process to create a new column called margin_category
# If the profit_margin is less than 0, the margin_category should be "unprofitable"
# If the profit_margin is 0, the margin_category should be "break even"
# If the profit_margin is above 0, the margin_category should "profitable"
def margin_categorization(row):
    if row<0 :
        return 'unprofitable'
    elif row==0 :
      return'break even'
    elif row>0 :
        return'profitable'
# continue your code here

orders['margin_category']=orders['profit_margin'].apply(margin_categorization)
    
# apply the function to the orders dataframe 
# to create the new column 'margin_category'
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin,margin_category
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0,break even
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0,break even
2,ES-2018-853948,28/07/2018 00:00,29/07/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,77095.0,1488.0,0.0,break even
3,ES-2019-1912507,01/04/2019 00:00,05/04/2019 00:00,Same Day,MD-17860,OFF-PA-10001758,114.0,4,0.05,0.0,77095.0,1488.0,0.0,break even
4,ES-2019-2038080,25/03/2019 00:00,28/03/2019 00:00,Same Day,MD-17860,OFF-PA-10001758,114.0,4,0.05,0.0,8701.0,5636.0,0.0,break even

Use the new `margin_category` column to find how many orders in the dataset were unprofitable. There are multiple ways to do this!

In [42]:
# D. How many of our orders were unprofitable?
# Hint: use .shape[0] to get number of rows of the dataframe
# Your code here please
orders['margin_category'].value_counts()

margin_category
profitable      868533
break even      110130
unprofitable     11821
Name: count, dtype: int64

In [45]:
orders[orders['margin_category']=='unprofitable'].shape[0]

11821

In [19]:
# NO CODE HERE PLEASE

11821