# Exercise: Neural Networks

## 1. Import the required libraries in the cell below

In [1]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

## 2. Read the data

In [2]:
housing = pd.read_csv('data/sacramento_real_estate_transactions.csv')
housing.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

## 3. Conduct Exploratory Data Analysis

In [3]:
# Check data info
housing.info()

<class 'pandas.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   street     985 non-null    str
 1   city       985 non-null    str
 2   zip        985 non-null    int64
 3   state      985 non-null    str
 4   beds       985 non-null    int64
 5   baths      985 non-null    int64
 6   sq__ft     985 non-null    int64
 7   type       985 non-null    str
 8   sale_date  985 non-null    str
 9   price      985 non-null    int64
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), str(5)
memory usage: 92.5 KB

In [4]:
# Check for missing values
housing.isna().sum()

street       0
city         0
zip          0
state        0
beds         0
baths        0
sq__ft       0
type         0
sale_date    0
price        0
latitude     0
longitude    0
dtype: int64

In [5]:
# Check data types
housing.dtypes

street           str
city             str
zip            int64
state            str
beds           int64
baths          int64
sq__ft         int64
type             str
sale_date        str
price          int64
latitude     float64
longitude    float64
dtype: object

In [6]:
# Look at the Summary Stats.
housing.describe()

,zip,beds,baths,sq__ft,price,latitude,longitude
count,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000
mean,95750.697462,2.911675,1.776650,1312.918782,233715.951269,38.445121,-121.193371
std,85.176072,1.307932,0.895371,856.123224,139088.818896,5.103637,5.100670
min,95603.000000,0.000000,0.000000,-984.000000,-210944.000000,-121.503471,-121.551704
25%,95660.000000,2.000000,1.000000,950.000000,145000.000000,38.482704,-121.446119
50%,95762.000000,3.000000,2.000000,1304.000000,213750.000000,38.625932,-121.375799
75%,95828.000000,4.000000,2.000000,1718.000000,300000.000000,38.695589,-121.294893
max,95864.000000,8.000000,5.000000,5822.000000,884790.000000,39.020808,38.668433

In [7]:
# Cleaning Steps (if needed)
# There is one row with a negative price and swapped lat/long values -
# this is clearly a bad record, so we drop it.
housing = housing[housing['price'] > 0]

# Drop the single row with an 'Unkown' (typo) property type - not usable.
housing = housing[housing['type'] != 'Unkown']

housing.shape

(983, 12)

In [8]:
# Rows with sq__ft == 0 don't have real square footage recorded
# (mostly vacant-lot style listings) - drop them since sq__ft is a key feature.
housing = housing[housing['sq__ft'] > 0]
housing.shape

(813, 12)

In [9]:
# Reset the index after dropping rows
housing = housing.reset_index(drop=True)
housing.describe()

,zip,beds,baths,sq__ft,price,latitude,longitude
count,813.000000,813.000000,813.000000,813.000000,813.000000,813.000000,813.000000
mean,95761.400984,3.247232,1.961870,1591.892989,229471.130381,38.576931,-121.378533
std,85.357516,0.849012,0.669367,663.908347,119897.576889,0.126352,0.119730
min,95603.000000,1.000000,1.000000,484.000000,2000.000000,38.241514,-121.550527
25%,95670.000000,3.000000,2.000000,1144.000000,148750.000000,38.473814,-121.451444
50%,95820.000000,3.000000,2.000000,1419.000000,207973.000000,38.591618,-121.404999
75%,95828.000000,4.000000,2.000000,1851.000000,285000.000000,38.674864,-121.325730
max,95864.000000,8.000000,5.000000,5822.000000,884790.000000,39.008159,-120.597599

In [10]:
#change sale_date types

## 4. Split the Data & Pre-Processing
**Best Practice for Neural Network** Split your data before modeling into three part:

1. __The Training Set (The Textbook):__ This is the data the neural network actually looks at to learn. During the training loop, the network uses this data to adjust its **weights** and **biases** via backpropagation.

2. __The Validation Set (The Practice Quiz):__ This data evaluates the model *during* training to fine-tune settings. The model does not learn its weights from this data. Instead, the it uses the validation score to choose **hyperparameters** (like learning rate, number of layers, or node count) and to decide when to stop training (**early stopping**).


3. __The Test Set (The Final Exam):__ This data provides an unbiased, final evaluation of the model's real-world performance. This dataset is locked away until training is completely finished. It is only used *once* at the very end to see how well the network performs on truly unseen data.

__Typical Split Ratios__

Depending on the size of your total dataset, data scientists generally use these proportions:

| Dataset Size | Train | Validation | Test |
| :--- | :--- | :--- | :--- |
| **Traditional (Small/Medium Data)** | 60% | 20% | 20% |
| **Modern Deep Learning (Millions of Rows)** | 98% | 1% | 1% |

In [11]:
# Select the Features and Target
X = housing[['sq__ft']]
y = housing['price']

In [12]:
# Split to Train Test & Validation
# First split off the Test set (the "Final Exam")
X_train_all, X_test, y_train_all, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

# Then split the remaining data into Train and Validation (the "Practice Quiz")
X_train, X_val, y_train, y_val = train_test_split(
    X_train_all, y_train_all, test_size=0.20, random_state=42)

print(X_train.shape, X_val.shape, X_test.shape)

(520, 1) (130, 1) (163, 1)

In [13]:
# IMPORTANT: Scale the features for Neural Networks
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Also scale the "all training" set (train + val) since Linear Regression
# and later models are trained on it
X_train_all_scaled = scaler.transform(X_train_all)

## 5. Linear Regression

In [14]:
# Initialize LinearRegression model
lr = LinearRegression()

In [15]:
# Fit and check the Training Score
lr.fit(X_train_all, y_train_all)
lr.score(X_train_all, y_train_all)

0.49925583857152667

In [16]:
# Predict and check the Testing Score
y_pred_lr = lr.predict(X_test)
lr.score(X_test, y_test)

0.39788582018348173

In [17]:
# Evaluate the model
# Coefficient
print('Coefficient:', lr.coef_)

# Intercept
print('Intercept:', lr.intercept_)

# RMSE
print('RMSE:', root_mean_squared_error(y_test, y_pred_lr))

Coefficient: [125.62893564]
Intercept: 29497.568792874372
RMSE: 87462.31374512309

## 6. Build a Single Neural Network
Creating a model in `keras` entails a few steps:
1. Create your network topology
2. Compile your model
3. Fit your model
   
**Important Note on Regression:**
Because we are predicting a continuous value (house price), our network is performing regression, not classification. 
* Your **hidden layers** should generally use the `relu` activation function.
* Your **output layer** must have exactly **1 neuron** and **no activation function** (or `activation='linear'`) so it can predict any continuous number.
* When compiling, use `loss='mse'` (Mean Squared Error) and `metrics=['mae']` (Mean Absolute Error) so we can see the error in actual dollar amounts.

In [18]:
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))            # 1 feature (sq__ft) coming in
model.add(Dense(1, activation='linear'))  # output layer: 1 neuron, no/linear activation

# Step 2: Compile
model.compile(loss='mse', metrics=['mae'])

# Step 3: Fit
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val))

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 68708024320.0000 - mae: 233264.8281 - val_loss: 65196670976.0000 - val_mae: 220649.6250

In [19]:
# Model Weights
model.weights

[<Variable path=sequential/dense/kernel, shape=(1, 1), dtype=float32, value=[[1.5138211]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[0.02549207]>]

In [20]:
# Model Summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6 (28.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4 (20.00 B)

## 7. Stacking Multiple Neurons

#### Shallow NN

In [21]:
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3))              # hidden layer with 3 neurons
model.add(Dense(1))              # output layer

# Step 2: Compile
model.compile(loss='mse', metrics=['mae'])

# Step 3: Fit
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val))

17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 68708458496.0000 - mae: 233264.7969 - val_loss: 65196961792.0000 - val_mae: 220649.2969

In [22]:
# Model Weights
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(1, 3), dtype=float32, value=[[0.222762  0.6080705 1.0738325]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(3,), dtype=float32, value=[ 0.02501933 -0.02459144 -0.02484054]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(3, 1), dtype=float32, value=[[ 0.9680462 ]
  [-0.24427333]
  [-1.0210838 ]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(1,), dtype=float32, value=[0.02492294]>]

In [23]:
# Model Summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 22 (92.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12 (52.00 B)

#### Deep Network

In [24]:
# use multiple hidden layers with different neurons

# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(30))
model.add(Dense(20))
model.add(Dense(15))
model.add(Dense(1))              # output layer

# Step 2: Compile
model.compile(loss='mse', metrics=['mae'])

# Step 3: Fit
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val))

17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 68708126720.0000 - mae: 233264.5938 - val_loss: 65196511232.0000 - val_mae: 220649.0156

In [25]:
# Model Weights
model.weights

[<Variable path=sequential_2/dense_3/kernel, shape=(1, 30), dtype=float32, value=[[ 0.34810877  0.08372881 -0.04958724  0.08115898 -0.24507831  0.11633919
    0.18536976 -0.2319394   0.3917471  -0.18120344 -0.2902971   0.1102142
   -0.2229796  -0.17851563 -0.09223852 -0.21854763  0.13223274 -0.00553826
   -0.2462144  -0.24655701 -0.2958319   0.2984706  -0.21079025 -0.21232778
   -0.19136946 -0.13635483  0.4240632  -0.2662403  -0.2307059  -0.0618221 ]]>,
 <Variable path=sequential_2/dense_3/bias, shape=(30,), dtype=float32, value=[ 0.02897051 -0.02552911 -0.02685786  0.02701112 -0.02708175  0.00297697
   0.00711433 -0.02746197 -0.00575178 -0.02816702 -0.01175436  0.02957314
  -0.02794633 -0.02879754  0.02404857  0.02403044 -0.02548232 -0.02667475
  -0.02430701 -0.028396    0.0253428   0.03128735  0.02823014  0.02140348
  -0.02806418  0.0204159   0.0304393  -0.02725031  0.01637981 -0.02610265]>,
 <Variable path=sequential_2/dense_4/kernel, shape=(30, 20), dtype=float32, value=[[-5.84465601e-02  1.72732323e-01 -1.46077186e-01  2.66443282e-01
    1.39497235e-01  7.08491951e-02 -2.84082532e-01  1.56467974e-01
   -2.47960359e-01  3.23941648e-01  2.96106905e-01 -1.83693022e-01
   -1.26971109e-02 -3.66149336e-01  3.31634209e-02  2.85744339e-01
    2.24647239e-01  1.45421922e-01  9.52858254e-02 -9.43415165e-02]
  [ 2.75346011e-01 -1.83151364e-01 -8.65360722e-02 -6.83365613e-02
    9.56782326e-02  1.10024594e-01 -2.62136906e-01 -1.54857516e-01
   -1.77338630e-01 -2.10178152e-01 -2.34949082e-01  4.61331643e-02
   -4.08569165e-03  3.09641659e-01  2.43745163e-01 -9.33462083e-02
   -8.81850347e-02 -2.49298975e-01  5.00994585e-02 -1.50592133e-01]
  [ 1.51848748e-01 -3.43756266e-02 -2.48093992e-01  1.86809391e-01
   -1.32050157e-01 -4.74176556e-02 -1.79222897e-01  7.36909509e-02
    2.79590964e-01  6.17872141e-02 -2.80993849e-01  1.28160849e-01
    1.55841619e-01  2.72507071e-01  3.75130922e-01  3.02418083e-01
    3.02103162e-01  1.74687788e-01  1.68804914e-01  1.50457362e-03]
  [-1.55083209e-01  1.68971434e-01  7.68218786e-02 -3.59977454e-01
    2.35529944e-01  3.15938406e-02  2.95296729e-01  3.56979430e-01
   -1.05753496e-01 -1.30404264e-01 -1.07664065e-02 -1.06204130e-01
    2.03791875e-02  6.27533421e-02 -2.21712530e-01 -4.50840145e-02
   -2.18004629e-01 -2.32508853e-01 -1.86344177e-01  1.05022304e-01]
  [ 6.94761649e-02 -2.37806574e-01 -1.29313111e-01 -2.31634393e-01
    1.68675140e-01  2.41166353e-01 -1.80370331e-01  4.47441153e-02
    3.46228123e-01  2.58359492e-01 -4.90512215e-02  3.15735459e-01
    6.03676923e-02 -4.16392609e-02 -3.34207192e-02 -3.18262160e-01
   -2.26601958e-01 -2.35337883e-01 -2.15749256e-02 -1.71976954e-01]
  [ 1.93843413e-02 -1.62949990e-02  1.08815692e-01 -3.27483788e-02
   -2.14496002e-01 -1.25009105e-01 -2.05681115e-01  9.64097306e-02
   -3.30391914e-01  3.14380437e-01 -3.27409478e-04 -2.68323999e-02
   -3.22180152e-01  1.49902210e-01 -1.67733148e-01  2.23179594e-01
    3.25807482e-01 -1.10289335e-01  2.01230094e-01 -1.07263885e-01]
  [ 8.04239959e-02 -3.43214720e-01  1.54694781e-01 -1.68582410e-01
   -8.16051662e-02 -3.40695500e-01 -2.75178552e-01 -1.01533890e-01
    4.89899926e-02  1.17330514e-01  1.01705551e-01 -2.90232319e-02
   -2.78525297e-02  3.14246446e-01  6.87602721e-03 -2.90799797e-01
    6.61455393e-02  2.22245887e-01 -2.63951093e-01 -2.39550591e-01]
  [ 5.28154299e-02 -2.13445321e-01  1.45664766e-01  3.03913981e-01
    2.78867483e-01  2.40283728e-01  9.17826127e-03 -1.74378544e-01
    1.99933304e-03 -2.54059106e-01  2.39302576e-01  3.68836671e-02
   -5.33262827e-02  3.38036835e-01  2.78975189e-01 -1.61206707e-01
   -1.89597100e-01 -1.76890105e-01  1.50682434e-01 -2.17869893e-01]
  [ 6.29099235e-02  1.23570219e-01  3.63520026e-01 -9.63325845e-04
    2.94676125e-01  2.95630157e-01  2.30648339e-01  1.86687797e-01
    3.24521810e-01  2.59473454e-03  2.50502259e-01  2.94500768e-01
   -1.48092717e-01  1.74852729e-01 -2.74095647e-02  3.61688733e-01
   -1.80757925e-01  1.16335131e-01 -3.44869286e-01 -3.13062817e-01]
  [ 9.55600366e-02  3.16846460e-01 -3.06766659e-01 -2.80471444e-01
   -3.55477221e-02 -2.99758524e-01  2.55437136e-01 -2.31452361e-01
   -9.85822082e-02 -2.78650492e-01 -1.56324223e-01  2.92149991e-01
   -2.00723201e-01 -9.83144939e-02  2.33423859e-01 -6.11195453e-02
    1.04495130e-01 -1.62113622e-01 -1.87523633e-01 -1.65729150e-01]
  [ 1.99654534e-01  2.35024303e-01 -1.86707795e-01 -1.89892843e-01
    4.15597782e-02  5.31148836e-02  2.46846005e-02  1.75480366e-01
   -2.53217906e-01  2.56065220e-01  1.11837752e-01  1.99737117e-01
    3.16596925e-01  3.46189559e-01 -3.15871805e-01  1.83627188e-01
    3.47925007e-01 -2.46563151e-01 -1.53099120e-01  2.77408391e-01]
  [-1.16297856e-01 -2.93403447e-01  2.40817964e-01  2.76427746e-01
   -3.66130292e-01 -2.29044065e-01  2.69505233e-01 -1.82999954e-01
    1.31913319e-01 -1.29783824e-01  1.98019311e-01 -2.59079605e-01
    1.23801768e-01 -3.10366243e-01  2.58913189e-01 -2.58872271e-01
    2.45832846e-01  2.65421808e-01 -2.40052283e-01  2.62105674e-01]
  [-1.97940052e-01  3.19742262e-01 -1.28318936e-01 -2.64886886e-01
    1.20346032e-01 -6.81506917e-02  3.05901349e-01 -3.62522721e-01
    1.60439089e-01  1.71151921e-01  2.40764290e-01  1.94198683e-01
    2.89359689e-01  2.41205037e-01 -3.00669312e-01 -2.23352090e-01
    2.69976288e-01 -2.92203873e-01 -3.76984589e-02  2.50485569e-01]
  [-2.20458880e-01 -1.12308502e-01 -2.48881742e-01  2.95504600e-01
    3.21269691e-01 -2.81391591e-01 -4.74365875e-02 -3.58443916e-01
    3.49593200e-02 -2.72950619e-01  2.40996525e-01 -1.13096312e-01
    1.91859305e-01 -2.07841903e-01 -9.02965739e-02 -1.41296461e-01
    2.04144895e-01  1.91913426e-01  3.51038545e-01  1.45877212e-01]
  [ 3.90472636e-02  1.22670293e-01 -1.22360311e-01 -3.09212148e-01
   -2.67806649e-01 -2.74212301e-01  3.20665777e-01 -6.09369054e-02
   -3.14123839e-01  4.17403504e-02  7.51035437e-02 -3.38030189e-01
    1.33745700e-01 -1.25630006e-01  2.65523314e-01  1.44507676e-01
   -2.00611353e-01  2.42988095e-01 -1.59175634e-01 -1.08463638e-01]
  [ 6.91013858e-02  2.70542875e-02  2.77429700e-01  8.66749436e-02
   -4.35430594e-02 -2.32861310e-01  5.48930876e-02 -8.91432017e-02
   -3.18299621e-01  1.11073978e-01 -2.81435817e-01 -2.68591046e-01
   -1.87774435e-01  3.14980298e-01  8.32729563e-02 -2.62441039e-02
    5.27344719e-02 -1.11686900e-01 -3.26836199e-01  3.24471295e-01]
  [-1.47232756e-01  3.66922505e-02 -2.93571264e-01  1.64678320e-01
   -2.08676144e-01 -2.97000706e-01  1.30511736e-02  4.78546768e-02
    2.50208080e-01 -2.40822226e-01  1.09048434e-01  2.47795612e-01
   -1.05548009e-01  1.98858336e-01  2.56171405e-01 -2.92123795e-01
    1.64049685e-01 -3.10895830e-01 -1.48555217e-02 -2.06013173e-01]
  [ 1.47871792e-01  3.61598283e-01 -1.14468269e-01  1.27330586e-01
   -3.05893779e-01  1.56661510e-01  1.54680356e-01 -3.11464816e-01
    2.27370456e-01 -2.83729196e-01  3.47143620e-01  1.17574252e-01
   -9.24431235e-02 -5.74916154e-02 -1.24937348e-01 -1.90848112e-01
    2.11386696e-01 -1.82601750e-01  2.50239313e-01  1.59572572e-01]
  [-2.16395855e-01  4.19223681e-02  1.82696670e-01 -1.77644357e-01
   -9.04053599e-02  1.09457439e-02  3.31286013e-01  1.11963861e-01
   -1.74943298e-01 -9.53235775e-02  1.45449758e-01 -2.23624662e-01
    4.67103394e-03  2.87494332e-01  2.41672039e-01 -2.76362211e-01
   -1.13564901e-01 -1.16359986e-01  3.36357430e-02 -2.03043088e-01]
  [-3.11542660e-01 -2.09648944e-02 -1.15316972e-01  1.15660476e-02
    2.55418986e-01 -2.82406002e-01 -2.97073394e-01  1.26745328e-02
    2.89283335e-01  8.60449970e-02  2.62148798e-01 -3.68412822e-01
   -2.85410851e-01 -1.96560457e-01  2.86244988e-01 -2.66020447e-01
    6.79742172e-03  6.45180941e-02  1.78302184e-01 -2.47286439e-01]
  [ 3.21692139e-01  2.98108160e-01  1.58812031e-01  2.53902495e-01
    6.66198358e-02  1.74369559e-01  3.68628018e-02  1.31735101e-01
   -2.55099654e-01  1.18898027e-01  3.09212029e-01  1.73939630e-01
   -1.45034462e-01 -3.21570158e-01  1.00647219e-01 -3.85013111e-02
   -3.12700272e-01  2.67975092e-01 -7.20722154e-02 -1.54724404e-01]
  [ 2.90574312e-01 -4.83204424e-02  1.73918620e-01  2.75302827e-01
   -4.48999405e-02 -1.88116580e-02 -2.26194501e-01  3.43626589e-01
    2.42609039e-01  7.68556967e-02  7.67317936e-02  2.14728206e-01
   -2.86321193e-01  3.49861942e-02 -1.65222168e-01  2.92367041e-01
   -1.10283196e-01  4.26117554e-02  1.60080157e-02  1.09680191e-01]
  [ 4.38095257e-02  1.68680437e-02 -2.01443434e-01  3.03163975e-01
    5.99205010e-02  3.81888151e-02 -1.51402280e-01  2.89243877e-01
    8.15649554e-02  1.18385620e-01 -1.64761364e-01  1.26022995e-01
   -3.44409436e-01  2.68647764e-02  2.19622906e-02 -1.84550226e-01
   -1.96683124e-01  4.66199853e-02 -2.67429411e-01 -5.27156051e-03]
  [ 1.62131280e-01 -1.85679927e-01  2.99012177e-02 -1.75405130e-01
    3.23567986e-01 -2.57340312e-01 -3.01141262e-01  2.96857804e-01
    9.48608518e-02  1.93685845e-01  2.72558089e-02 -3.39222282e-01
   -3.53857204e-02  2.56155849e-01  1.12876005e-01 -7.45678395e-02
    1.98285822e-02  1.37592718e-01  1.29303575e-01  3.43311913e-02]
  [-6.44348785e-02 -7.54645988e-02  1.46291137e-01 -8.47827792e-02
    1.10656567e-01  4.42805961e-02 -2.49881998e-01  2.04869568e-01
    1.29548952e-01  2.70587683e-01 -1.92279313e-02 -4.08611111e-02
    2.01383099e-01  1.43443972e-01  2.38785654e-01 -1.32765546e-01
    3.60090017e-01 -1.62713319e-01 -9.91840032e-04  2.41822198e-01]
  [ 3.17908555e-01  3.37234527e-01  2.77799070e-01  2.45696038e-01
    2.85872787e-01  1.48891211e-01 -1.94584176e-01  1.94228053e-01
   -1.71458885e-01 -2.25361168e-01 -3.31173927e-01  9.43088904e-02
    3.09478819e-01 -9.40180477e-03  2.89307088e-01  2.49130830e-01
    7.96457753e-02 -1.66131064e-01  6.59181178e-02  9.11685526e-02]
  [ 1.54087007e-01 -1.46769375e-01 -1.81060091e-01 -5.11799427e-03
   -2.32024133e-01  1.12368166e-01 -1.94345132e-01  2.81737804e-01
   -2.14840725e-01  6.29312322e-02 -3.05934787e-01  3.69741321e-01
   -1.63140148e-01  1.74051493e-01  4.26050909e-02 -3.00487936e-01
    2.65093833e-01  3.31759781e-01 -3.12668830e-01  3.39000046e-01]
  [ 1.32638305e-01  9.50303152e-02 -8.55450109e-02 -3.68011035e-02
    2.97247302e-02 -2.20253438e-01  1.69170454e-01 -4.64475900e-02
    3.19711357e-01 -3.42470795e-01  3.21627170e-01 -1.50535047e-01
    1.91797078e-01  1.25066414e-01 -2.94196784e-01  3.20467830e-01
    2.72165716e-01 -4.34109233e-02  5.09945899e-02 -1.18780516e-01]
  [ 8.45490843e-02  2.40514755e-01 -2.48271719e-01  1.33739114e-01
   -1.49336904e-01 -2.37157121e-01  1.35918230e-01 -1.63943231e-01
   -5.52483685e-02  1.69384331e-01  2.16870978e-01  2.71917373e-01
    2.41907701e-01  2.71497250e-01 -1.60021689e-02 -2.03505263e-01
   -3.11569683e-02  1.84190094e-01  2.21470762e-02 -3.07805906e-03]
  [ 3.18293959e-01 -1.12167180e-01  2.68956304e-01 -7.48978881e-03
   -2.42751747e-01  2.82270581e-01 -2.21791163e-01 -5.61464280e-02
    3.57799500e-01 -1.53291196e-01  2.86304712e-01  1.68521240e-01
    4.47393022e-02  3.66298586e-01  1.34412318e-01  7.25160465e-02
    3.60463440e-01 -2.30877653e-01  1.16677873e-01  7.70609453e-02]]>,
 <Variable path=sequential_2/dense_4/bias, shape=(20,), dtype=float32, value=[ 0.02458711 -0.02852637  0.02625633 -0.02041591 -0.02425509 -0.02393957
   0.01514664  0.02676471 -0.02548026  0.02579177  0.00580388  0.03020301
   0.02231343 -0.02652584 -0.02845196  0.02801592 -0.02519519  0.02576828
  -0.02287121  0.02519633]>,
 <Variable path=sequential_2/dense_5/kernel, shape=(20, 15), dtype=float32, value=[[ 0.20872243 -0.23628195 -0.11252896  0.11855792  0.3215507  -0.01869985
    0.34355885  0.21446505 -0.2262936  -0.40401903 -0.23349053 -0.00701005
   -0.11500642 -0.14867897  0.1772229 ]
  [ 0.0356369  -0.13084109  0.22164679  0.13572092 -0.3058239   0.10082145
    0.04185846  0.0057583  -0.21866359 -0.10297183 -0.41630408 -0.12465256
   -0.39558983 -0.0035814   0.14581713]
  [-0.04494825  0.25753528 -0.22945338 -0.17488497 -0.3349148  -0.38451156
   -0.29574573 -0.132285    0.2250515  -0.32860285  0.17064469  0.1826619
    0.36263892  0.0782316   0.26308692]
  [-0.00852867  0.17715871  0.35351494  0.2606037  -0.3438346   0.39433143
    0.19423679 -0.3200716  -0.23095855  0.06892931 -0.00596658  0.29343364
    0.3070945   0.03098585 -0.29047462]
  [-0.2402959   0.17002997 -0.397198   -0.32507917 -0.35488924 -0.01279813
   -0.21042123  0.18213557 -0.04591432 -0.10679492  0.10150735 -0.08531539
    0.06061044  0.32208514 -0.3574454 ]
  [-0.00885225  0.29015672 -0.34340778  0.10771802  0.13060868 -0.19272904
   -0.3796845  -0.22748838  0.11178707 -0.17622443  0.13437454  0.07153846
    0.1832004   0.42502633 -0.07500251]
  [-0.4228185  -0.08135541 -0.37240648 -0.1643626  -0.22216277 -0.05921539
    0.30739555  0.2533272   0.18714376  0.06004776 -0.00606718 -0.33949518
    0.3558617   0.27089486 -0.25035197]
  [-0.3544604   0.32330683  0.30268723 -0.05859655 -0.43834016 -0.17806596
    0.01533586  0.07891127 -0.21428208 -0.06326913  0.03584115  0.32329056
   -0.27216136 -0.29656526 -0.05239753]
  [-0.12004412  0.02429854 -0.2513298   0.3547864  -0.13706928  0.40277296
   -0.03228271  0.2792352  -0.0327324   0.17825472 -0.28721938 -0.20918289
   -0.03601135 -0.15354793 -0.18764096]
  [ 0.37506753  0.04602976  0.21634324 -0.30081588 -0.2905758   0.35202
    0.09029841 -0.2281486  -0.21974549  0.09882357 -0.14208926 -0.07434282
    0.3332565  -0.352693    0.36674643]
  [ 0.25468913  0.34034944 -0.3351385  -0.06013958 -0.36146694  0.08351685
   -0.21678211 -0.07338664 -0.29881704  0.1914335  -0.22883198  0.22569777
    0.3829868   0.38678682 -0.36250478]
  [ 0.0307575  -0.21473908  0.05600813  0.18866795  0.06154567 -0.16363943
   -0.17565864 -0.13554756  0.2649276  -0.4309407   0.2430582   0.02582191
    0.31864154 -0.38506562  0.12081254]
  [-0.3174507   0.21498677  0.24845968 -0.07244616 -0.24298501  0.31078508
    0.24551344  0.09704335  0.3404682  -0.08881535  0.26085338  0.15468153
   -0.0247516  -0.02093893 -0.01649513]
  [-0.23774129 -0.28148505 -0.19841693 -0.1918214  -0.29437372 -0.32881138
   -0.34822005 -0.35899132 -0.01690959 -0.38207263 -0.02263173  0.02718412
   -0.35472193 -0.04327957 -0.38853398]
  [ 0.17938067 -0.42306706 -0.18055195 -0.16574028  0.00064465  0.19341594
    0.10770893  0.06657927  0.32452187  0.04674282 -0.3891235  -0.16399957
   -0.19415618  0.21855022  0.28207245]
  [-0.13061619  0.02619401  0.09597332 -0.42779616 -0.28624666 -0.14713939
    0.30821913 -0.32406998 -0.13327412  0.2707859  -0.03152325  0.03066972
    0.18527944 -0.22747333 -0.29443413]
  [-0.3299431   0.15850161 -0.29852757  0.34763253  0.2583026   0.37295333
    0.18830745  0.2820289   0.34119555  0.38368765 -0.24944535  0.17481807
   -0.19553243  0.37141663 -0.08673052]
  [ 0.10101236  0.18693183  0.42357486 -0.21461073  0.20091881  0.0631615
    0.35915494  0.3725723  -0.1654027   0.07389751 -0.08878443  0.3349541
   -0.09622966  0.20371358  0.13494088]
  [-0.16945031 -0.20441851  0.00414923 -0.20949292 -0.07824299 -0.28148124
   -0.41075748 -0.36490384  0.01690087  0.09953479 -0.20598626  0.09549718
   -0.14094365 -0.221912    0.15248668]
  [ 0.19038208 -0.01578716  0.11651229 -0.04204341 -0.05952863 -0.24213031
   -0.2489811   0.07705854 -0.33711195  0.12650329  0.30084363  0.1617628
   -0.3909442   0.1827053   0.30598304]]>,
 <Variable path=sequential_2/dense_5/bias, shape=(15,), dtype=float32, value=[ 0.02619667  0.02832525  0.0252297  -0.02496098 -0.02424052 -0.02517531
   0.02531859  0.02490951 -0.02531441 -0.02460865  0.02550682  0.02522323
   0.02517225  0.02337454  0.02513018]>,
 <Variable path=sequential_2/dense_6/kernel, shape=(15, 1), dtype=float32, value=[[ 0.12042382]
  [ 0.04421487]
  [ 0.5316409 ]
  [-0.4900121 ]
  [-0.06950756]
  [-0.60388577]
  [ 0.28829697]
  [ 0.57416564]
  [-0.34738535]
  [-0.09920201]
  [ 0.21737678]
  [ 0.43770295]
  [ 0.5963968 ]
  [ 0.04386893]
  [ 0.5209548 ]]>,
 <Variable path=sequential_2/dense_6/bias, shape=(1,), dtype=float32, value=[0.02499325]>]

In [26]:
# Model Summary
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 30)                  │              60 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 20)                  │             620 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 15)                  │             315 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,024 (7.91 KB)

 Trainable params: 1,011 (3.95 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,013 (3.96 KB)

## 8. Activation Functions

In [27]:
# from keras.layers import Activation
# Note: import Activation if you use it as a standalone layer

# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))     # hidden layer with relu activation
model.add(Dense(1, activation='linear'))   # output layer with linear activation

# Step 2: Compile
model.compile(loss='mse', metrics=['mae'])

# Step 3: Fit
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val))

17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 68708323328.0000 - mae: 233264.9531 - val_loss: 65196883968.0000 - val_mae: 220649.5156

In [28]:
# Model Weights
model.weights

[<Variable path=sequential_3/dense_7/kernel, shape=(1, 3), dtype=float32, value=[[-0.31815216  0.76532483 -0.534513  ]]>,
 <Variable path=sequential_3/dense_7/bias, shape=(3,), dtype=float32, value=[ 0.02657606 -0.02176572 -0.02528455]>,
 <Variable path=sequential_3/dense_8/kernel, shape=(3, 1), dtype=float32, value=[[ 0.91992676]
  [-0.06020916]
  [-0.8753258 ]]>,
 <Variable path=sequential_3/dense_8/bias, shape=(1,), dtype=float32, value=[0.02485139]>]

In [29]:
# Model Summary
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                      │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 22 (92.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12 (52.00 B)

## 9. Epochs

In [30]:
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))

# Step 2: Compile
model.compile(loss='mse' , metrics = ['mae'])

# Step 3: Fit
# 50 epochs means 50 complete passes of the training algorithm
# through the entire training dataset
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val),
          epochs=50)

Epoch 1/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 68708216832.0000 - mae: 233264.7344 - val_loss: 65196789760.0000 - val_mae: 220649.3438
Epoch 2/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68708192256.0000 - mae: 233264.6719 - val_loss: 65196777472.0000 - val_mae: 220649.2812
Epoch 3/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68708175872.0000 - mae: 233264.6562 - val_loss: 65196756992.0000 - val_mae: 220649.2500
Epoch 4/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708159488.0000 - mae: 233264.5781 - val_loss: 65196736512.0000 - val_mae: 220649.1719
Epoch 5/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68708134912.0000 - mae: 233264.5625 - val_loss: 65196711936.0000 - val_mae: 220649.1406
Epoch 6/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68708118528.0000 - mae: 233264.5156 - val_loss: 65196691456.0000 - val_mae: 220649.0781
Epoch 7/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708102144.0000 - mae: 233264.4844 - val_loss: 65196666880.0000 - val_mae: 220649.0312
Epoch 8/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708077568.0000 - mae: 233264.4375 - val_loss: 65196654592.0000 - val_mae: 220648.9688
Epoch 9/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68708057088.0000 - mae: 233264.3906 - val_loss: 65196621824.0000 - val_mae: 220648.9062
Epoch 10/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68708024320.0000 - mae: 233264.3125 - val_loss: 65196597248.0000 - val_mae: 220648.8594
Epoch 11/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707999744.0000 - mae: 233264.2969 - val_loss: 65196576768.0000 - val_mae: 220648.8125
Epoch 12/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707975168.0000 - mae: 233264.2188 - val_loss: 65196548096.0000 - val_mae: 220648.7344
Epoch 13/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68707942400.0000 - mae: 233264.1719 - val_loss: 65196519424.0000 - val_mae: 220648.6875
Epoch 14/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68707926016.0000 - mae: 233264.1094 - val_loss: 65196490752.0000 - val_mae: 220648.6094
Epoch 15/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707893248.0000 - mae: 233264.0469 - val_loss: 65196466176.0000 - val_mae: 220648.5469
Epoch 16/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707876864.0000 - mae: 233263.9688 - val_loss: 65196437504.0000 - val_mae: 220648.5000
Epoch 17/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707835904.0000 - mae: 233263.9219 - val_loss: 65196404736.0000 - val_mae: 220648.4219
Epoch 18/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707811328.0000 - mae: 233263.8438 - val_loss: 65196376064.0000 - val_mae: 220648.3438
Epoch 19/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707782656.0000 - mae: 233263.7812 - val_loss: 65196351488.0000 - val_mae: 220648.2656
Epoch 20/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707749888.0000 - mae: 233263.6875 - val_loss: 65196314624.0000 - val_mae: 220648.1875
Epoch 21/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707708928.0000 - mae: 233263.6094 - val_loss: 65196281856.0000 - val_mae: 220648.1094
Epoch 22/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707676160.0000 - mae: 233263.5312 - val_loss: 65196249088.0000 - val_mae: 220648.0312
Epoch 23/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707643392.0000 - mae: 233263.4844 - val_loss: 65196216320.0000 - val_mae: 220647.9531
Epoch 24/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707610624.0000 - mae: 233263.4062 - val_loss: 65196179456.0000 - val_mae: 220647.8594
Epoch 25/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68707586048.0000 - mae: 233263.3438 - val_loss: 65196146688.0000 - val_mae: 220647.7812
Epoch 26/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707549184.0000 - mae: 233263.2344 - val_loss: 65196109824.0000 - val_mae: 220647.7031
Epoch 27/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68707508224.0000 - mae: 233263.1875 - val_loss: 65196072960.0000 - val_mae: 220647.5938
Epoch 28/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68707467264.0000 - mae: 233263.1094 - val_loss: 65196032000.0000 - val_mae: 220647.5156
Epoch 29/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707426304.0000 - mae: 233262.9844 - val_loss: 65195995136.0000 - val_mae: 220647.4062
Epoch 30/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707385344.0000 - mae: 233262.9219 - val_loss: 65195950080.0000 - val_mae: 220647.3281
Epoch 31/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707352576.0000 - mae: 233262.7812 - val_loss: 65195913216.0000 - val_mae: 220647.2188
Epoch 32/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707303424.0000 - mae: 233262.7500 - val_loss: 65195868160.0000 - val_mae: 220647.1094
Epoch 33/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707258368.0000 - mae: 233262.6094 - val_loss: 65195831296.0000 - val_mae: 220647.0156
Epoch 34/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707217408.0000 - mae: 233262.5312 - val_loss: 65195790336.0000 - val_mae: 220646.9219
Epoch 35/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707168256.0000 - mae: 233262.4375 - val_loss: 65195745280.0000 - val_mae: 220646.8281
Epoch 36/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707135488.0000 - mae: 233262.3750 - val_loss: 65195704320.0000 - val_mae: 220646.7031
Epoch 37/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707086336.0000 - mae: 233262.2500 - val_loss: 65195655168.0000 - val_mae: 220646.5938
Epoch 38/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707037184.0000 - mae: 233262.1562 - val_loss: 65195606016.0000 - val_mae: 220646.4844
Epoch 39/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68706992128.0000 - mae: 233262.0312 - val_loss: 65195569152.0000 - val_mae: 220646.3594
Epoch 40/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68706942976.0000 - mae: 233261.9062 - val_loss: 65195511808.0000 - val_mae: 220646.2656
Epoch 41/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68706902016.0000 - mae: 233261.8281 - val_loss: 65195466752.0000 - val_mae: 220646.1406
Epoch 42/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68706844672.0000 - mae: 233261.7188 - val_loss: 65195421696.0000 - val_mae: 220646.0156
Epoch 43/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68706811904.0000 - mae: 233261.5938 - val_loss: 65195372544.0000 - val_mae: 220645.9062
Epoch 44/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68706742272.0000 - mae: 233261.4844 - val_loss: 65195323392.0000 - val_mae: 220645.7969
Epoch 45/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68706693120.0000 - mae: 233261.3906 - val_loss: 65195270144.0000 - val_mae: 220645.6562
Epoch 46/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68706643968.0000 - mae: 233261.2500 - val_loss: 65195220992.0000 - val_mae: 220645.5312
Epoch 47/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68706594816.0000 - mae: 233261.1250 - val_loss: 65195159552.0000 - val_mae: 220645.4062
Epoch 48/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68706537472.0000 - mae: 233261.0156 - val_loss: 65195110400.0000 - val_mae: 220645.2656
Epoch 49/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68706484224.0000 - mae: 233260.8594 - val_loss: 65195053056.0000 - val_mae: 220645.1406
Epoch 50/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68706426880.0000 - mae: 233260.7656 - val_loss: 65195003904.0000 - val_mae: 220645.0156

In [31]:
# Model Weights
model.weights

[<Variable path=sequential_4/dense_9/kernel, shape=(1, 3), dtype=float32, value=[[ 1.3684869 -1.7924807 -2.0055506]]>,
 <Variable path=sequential_4/dense_9/bias, shape=(3,), dtype=float32, value=[0.86086124 0.7412715  0.86818796]>,
 <Variable path=sequential_4/dense_10/kernel, shape=(3, 1), dtype=float32, value=[[1.09295   ]
  [0.7768563 ]
  [0.98111814]]>,
 <Variable path=sequential_4/dense_10/bias, shape=(1,), dtype=float32, value=[0.8559053]>]

In [32]:
# Model Summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                      │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 22 (92.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12 (52.00 B)

## 10. Batch size (Chunks)

In [33]:
# Use the validation
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))

# Step 2: Compile
model.compile(loss='mse' , metrics = ['mae'])

# Step 3: Fit
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val),
          epochs=50,
          batch_size=64)

Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 68708118528.0000 - mae: 233264.3281 - val_loss: 65196654592.0000 - val_mae: 220648.7344
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68708110336.0000 - mae: 233264.2969 - val_loss: 65196642304.0000 - val_mae: 220648.7031
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 68708085760.0000 - mae: 233264.2500 - val_loss: 65196630016.0000 - val_mae: 220648.6719
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68708077568.0000 - mae: 233264.2188 - val_loss: 65196613632.0000 - val_mae: 220648.6406
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68708073472.0000 - mae: 233264.2031 - val_loss: 65196605440.0000 - val_mae: 220648.5938
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68708057088.0000 - mae: 233264.1406 - val_loss: 65196584960.0000 - val_mae: 220648.5625
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68708032512.0000 - mae: 233264.1250 - val_loss: 65196580864.0000 - val_mae: 220648.5156
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68708032512.0000 - mae: 233264.0781 - val_loss: 65196564480.0000 - val_mae: 220648.5000
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68708016128.0000 - mae: 233264.0312 - val_loss: 65196552192.0000 - val_mae: 220648.4688
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 68708007936.0000 - mae: 233264.0156 - val_loss: 65196535808.0000 - val_mae: 220648.4062
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68707991552.0000 - mae: 233263.9844 - val_loss: 65196519424.0000 - val_mae: 220648.3750
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68707983360.0000 - mae: 233263.9375 - val_loss: 65196503040.0000 - val_mae: 220648.3438
Epoch 13/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68707966976.0000 - mae: 233263.9219 - val_loss: 65196494848.0000 - val_mae: 220648.3125
Epoch 14/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 68707950592.0000 - mae: 233263.8750 - val_loss: 65196478464.0000 - val_mae: 220648.2656
Epoch 15/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707934208.0000 - mae: 233263.8281 - val_loss: 65196462080.0000 - val_mae: 220648.2188
Epoch 16/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 68707926016.0000 - mae: 233263.7969 - val_loss: 65196445696.0000 - val_mae: 220648.1719
Epoch 17/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707917824.0000 - mae: 233263.7500 - val_loss: 65196429312.0000 - val_mae: 220648.1406
Epoch 18/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 68707901440.0000 - mae: 233263.7188 - val_loss: 65196417024.0000 - val_mae: 220648.0938
Epoch 19/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68707876864.0000 - mae: 233263.6875 - val_loss: 65196400640.0000 - val_mae: 220648.0625
Epoch 20/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707868672.0000 - mae: 233263.6406 - val_loss: 65196388352.0000 - val_mae: 220648.0000
Epoch 21/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707852288.0000 - mae: 233263.6094 - val_loss: 65196367872.0000 - val_mae: 220647.9688
Epoch 22/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707835904.0000 - mae: 233263.5781 - val_loss: 65196351488.0000 - val_mae: 220647.9062
Epoch 23/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68707811328.0000 - mae: 233263.5312 - val_loss: 65196335104.0000 - val_mae: 220647.8750
Epoch 24/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707799040.0000 - mae: 233263.4844 - val_loss: 65196318720.0000 - val_mae: 220647.8281
Epoch 25/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 68707782656.0000 - mae: 233263.4688 - val_loss: 65196302336.0000 - val_mae: 220647.7812
Epoch 26/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707766272.0000 - mae: 233263.4219 - val_loss: 65196285952.0000 - val_mae: 220647.7344
Epoch 27/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707741696.0000 - mae: 233263.3750 - val_loss: 65196265472.0000 - val_mae: 220647.6875
Epoch 28/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68707733504.0000 - mae: 233263.3125 - val_loss: 65196249088.0000 - val_mae: 220647.6250
Epoch 29/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 68707717120.0000 - mae: 233263.2812 - val_loss: 65196232704.0000 - val_mae: 220647.5938
Epoch 30/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 68707692544.0000 - mae: 233263.2188 - val_loss: 65196220416.0000 - val_mae: 220647.5312
Epoch 31/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707684352.0000 - mae: 233263.2031 - val_loss: 65196195840.0000 - val_mae: 220647.5000
Epoch 32/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707659776.0000 - mae: 233263.1406 - val_loss: 65196171264.0000 - val_mae: 220647.4375
Epoch 33/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707643392.0000 - mae: 233263.1094 - val_loss: 65196154880.0000 - val_mae: 220647.4062
Epoch 34/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707627008.0000 - mae: 233263.0469 - val_loss: 65196134400.0000 - val_mae: 220647.3438
Epoch 35/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 68707602432.0000 - mae: 233263.0000 - val_loss: 65196122112.0000 - val_mae: 220647.2812
Epoch 36/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707586048.0000 - mae: 233262.9375 - val_loss: 65196101632.0000 - val_mae: 220647.2188
Epoch 37/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68707561472.0000 - mae: 233262.9062 - val_loss: 65196085248.0000 - val_mae: 220647.1875
Epoch 38/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68707549184.0000 - mae: 233262.8594 - val_loss: 65196064768.0000 - val_mae: 220647.1406
Epoch 39/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707532800.0000 - mae: 233262.8125 - val_loss: 65196044288.0000 - val_mae: 220647.0781
Epoch 40/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707508224.0000 - mae: 233262.7812 - val_loss: 65196019712.0000 - val_mae: 220647.0312
Epoch 41/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68707483648.0000 - mae: 233262.7188 - val_loss: 65195999232.0000 - val_mae: 220646.9688
Epoch 42/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707467264.0000 - mae: 233262.6562 - val_loss: 65195982848.0000 - val_mae: 220646.9062
Epoch 43/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 68707442688.0000 - mae: 233262.6250 - val_loss: 65195958272.0000 - val_mae: 220646.8438
Epoch 44/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 68707426304.0000 - mae: 233262.5625 - val_loss: 65195937792.0000 - val_mae: 220646.7969
Epoch 45/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 68707401728.0000 - mae: 233262.5000 - val_loss: 65195917312.0000 - val_mae: 220646.7500
Epoch 46/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 68707385344.0000 - mae: 233262.4531 - val_loss: 65195892736.0000 - val_mae: 220646.6875
Epoch 47/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707360768.0000 - mae: 233262.4062 - val_loss: 65195872256.0000 - val_mae: 220646.6250
Epoch 48/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 68707336192.0000 - mae: 233262.3594 - val_loss: 65195851776.0000 - val_mae: 220646.5781
Epoch 49/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68707311616.0000 - mae: 233262.2812 - val_loss: 65195827200.0000 - val_mae: 220646.5000
Epoch 50/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 68707287040.0000 - mae: 233262.2500 - val_loss: 65195810816.0000 - val_mae: 220646.4688

In [34]:
# Model Weights
model.weights

[<Variable path=sequential_5/dense_11/kernel, shape=(1, 3), dtype=float32, value=[[ 0.5380359  -1.5803958  -0.45800984]]>,
 <Variable path=sequential_5/dense_11/bias, shape=(3,), dtype=float32, value=[0.324721   0.45979604 0.46495277]>,
 <Variable path=sequential_5/dense_12/kernel, shape=(3, 1), dtype=float32, value=[[0.361    ]
  [1.68041  ]
  [1.0434587]]>,
 <Variable path=sequential_5/dense_12/bias, shape=(1,), dtype=float32, value=[0.457996]>]

In [35]:
# Model Summary
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 22 (92.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12 (52.00 B)

Try a different batch size. 

__Note:__ the best practice to have the value in powers of 2

In [36]:
# Use the validation
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))

# Step 2: Compile
model.compile(loss='mse' , metrics = ['mae'])

# Step 3: Fit
# try a different (power of 2) batch size
model.fit(X_train_scaled, y_train,
          validation_data=(X_val_scaled, y_val),
          epochs=50,
          batch_size=32)

Epoch 1/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 68708352000.0000 - mae: 233264.9375 - val_loss: 65196916736.0000 - val_mae: 220649.5469
Epoch 2/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68708331520.0000 - mae: 233264.9219 - val_loss: 65196904448.0000 - val_mae: 220649.5156
Epoch 3/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68708323328.0000 - mae: 233264.9062 - val_loss: 65196892160.0000 - val_mae: 220649.4844
Epoch 4/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68708306944.0000 - mae: 233264.8438 - val_loss: 65196875776.0000 - val_mae: 220649.4688
Epoch 5/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708282368.0000 - mae: 233264.7969 - val_loss: 65196851200.0000 - val_mae: 220649.4219
Epoch 6/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708274176.0000 - mae: 233264.7812 - val_loss: 65196838912.0000 - val_mae: 220649.4062
Epoch 7/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708249600.0000 - mae: 233264.7656 - val_loss: 65196818432.0000 - val_mae: 220649.3594
Epoch 8/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68708241408.0000 - mae: 233264.7031 - val_loss: 65196810240.0000 - val_mae: 220649.3125
Epoch 9/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68708216832.0000 - mae: 233264.6875 - val_loss: 65196789760.0000 - val_mae: 220649.2812
Epoch 10/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68708200448.0000 - mae: 233264.6406 - val_loss: 65196773376.0000 - val_mae: 220649.2500
Epoch 11/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68708184064.0000 - mae: 233264.6094 - val_loss: 65196765184.0000 - val_mae: 220649.2031
Epoch 12/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68708184064.0000 - mae: 233264.5781 - val_loss: 65196744704.0000 - val_mae: 220649.1562
Epoch 13/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68708151296.0000 - mae: 233264.5312 - val_loss: 65196732416.0000 - val_mae: 220649.1250
Epoch 14/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708143104.0000 - mae: 233264.5156 - val_loss: 65196703744.0000 - val_mae: 220649.0938
Epoch 15/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68708118528.0000 - mae: 233264.4688 - val_loss: 65196687360.0000 - val_mae: 220649.0625
Epoch 16/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68708102144.0000 - mae: 233264.4531 - val_loss: 65196679168.0000 - val_mae: 220649.0156
Epoch 17/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68708085760.0000 - mae: 233264.4219 - val_loss: 65196658688.0000 - val_mae: 220648.9531
Epoch 18/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68708065280.0000 - mae: 233264.3750 - val_loss: 65196650496.0000 - val_mae: 220648.9219
Epoch 19/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68708048896.0000 - mae: 233264.3281 - val_loss: 65196621824.0000 - val_mae: 220648.8906
Epoch 20/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68708032512.0000 - mae: 233264.2812 - val_loss: 65196605440.0000 - val_mae: 220648.8281
Epoch 21/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68708007936.0000 - mae: 233264.2656 - val_loss: 65196584960.0000 - val_mae: 220648.7656
Epoch 22/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707991552.0000 - mae: 233264.1719 - val_loss: 65196564480.0000 - val_mae: 220648.7344
Epoch 23/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68707966976.0000 - mae: 233264.1875 - val_loss: 65196544000.0000 - val_mae: 220648.6875
Epoch 24/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707942400.0000 - mae: 233264.0781 - val_loss: 65196519424.0000 - val_mae: 220648.6406
Epoch 25/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68707934208.0000 - mae: 233264.0469 - val_loss: 65196486656.0000 - val_mae: 220648.5781
Epoch 26/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707901440.0000 - mae: 233264.0000 - val_loss: 65196470272.0000 - val_mae: 220648.5156
Epoch 27/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707860480.0000 - mae: 233263.9219 - val_loss: 65196445696.0000 - val_mae: 220648.4844
Epoch 28/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707844096.0000 - mae: 233263.8906 - val_loss: 65196412928.0000 - val_mae: 220648.4062
Epoch 29/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707811328.0000 - mae: 233263.8125 - val_loss: 65196392448.0000 - val_mae: 220648.3750
Epoch 30/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707790848.0000 - mae: 233263.7656 - val_loss: 65196371968.0000 - val_mae: 220648.2812
Epoch 31/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707766272.0000 - mae: 233263.7188 - val_loss: 65196343296.0000 - val_mae: 220648.2500
Epoch 32/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707733504.0000 - mae: 233263.6562 - val_loss: 65196310528.0000 - val_mae: 220648.1406
Epoch 33/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707708928.0000 - mae: 233263.5781 - val_loss: 65196277760.0000 - val_mae: 220648.0938
Epoch 34/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707684352.0000 - mae: 233263.5312 - val_loss: 65196253184.0000 - val_mae: 220648.0156
Epoch 35/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707643392.0000 - mae: 233263.4844 - val_loss: 65196220416.0000 - val_mae: 220647.9375
Epoch 36/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707610624.0000 - mae: 233263.4219 - val_loss: 65196183552.0000 - val_mae: 220647.8594
Epoch 37/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707577856.0000 - mae: 233263.3281 - val_loss: 65196158976.0000 - val_mae: 220647.7969
Epoch 38/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707540992.0000 - mae: 233263.2344 - val_loss: 65196122112.0000 - val_mae: 220647.7031
Epoch 39/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707516416.0000 - mae: 233263.2031 - val_loss: 65196093440.0000 - val_mae: 220647.6406
Epoch 40/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707483648.0000 - mae: 233263.0938 - val_loss: 65196060672.0000 - val_mae: 220647.5469
Epoch 41/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68707442688.0000 - mae: 233263.0312 - val_loss: 65196019712.0000 - val_mae: 220647.5000
Epoch 42/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707401728.0000 - mae: 233262.9375 - val_loss: 65195991040.0000 - val_mae: 220647.3906
Epoch 43/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707368960.0000 - mae: 233262.8594 - val_loss: 65195950080.0000 - val_mae: 220647.3125
Epoch 44/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707328000.0000 - mae: 233262.7656 - val_loss: 65195913216.0000 - val_mae: 220647.2031
Epoch 45/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68707295232.0000 - mae: 233262.6875 - val_loss: 65195872256.0000 - val_mae: 220647.1250
Epoch 46/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68707258368.0000 - mae: 233262.6094 - val_loss: 65195835392.0000 - val_mae: 220647.0156
Epoch 47/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 68707217408.0000 - mae: 233262.5156 - val_loss: 65195798528.0000 - val_mae: 220646.9375
Epoch 48/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707176448.0000 - mae: 233262.4531 - val_loss: 65195757568.0000 - val_mae: 220646.8125
Epoch 49/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707135488.0000 - mae: 233262.3438 - val_loss: 65195712512.0000 - val_mae: 220646.7344
Epoch 50/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68707086336.0000 - mae: 233262.2656 - val_loss: 65195671552.0000 - val_mae: 220646.6406

In [37]:
# Model Weights
model.weights

[<Variable path=sequential_6/dense_13/kernel, shape=(1, 3), dtype=float32, value=[[-0.8516436  1.618362  -1.4185404]]>,
 <Variable path=sequential_6/dense_13/bias, shape=(3,), dtype=float32, value=[0.35119838 0.51117486 0.86864465]>,
 <Variable path=sequential_6/dense_14/kernel, shape=(3, 1), dtype=float32, value=[[0.5751441 ]
  [0.60568917]
  [0.8501351 ]]>,
 <Variable path=sequential_6/dense_14/bias, shape=(1,), dtype=float32, value=[0.8549081]>]

In [38]:
# Model Summary
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                     │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 22 (92.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 12 (52.00 B)

## 11. History

**The Three Main Reasons to Use History**
  1. To Spot Overfitting
  2. To Visualise the Learning Curve
  3. To Know When to Stop Training

By saving the output of `model.fit()` to a variable (usually called `history`), Keras keeps a record of the training loss and validation loss at the end of each epoch. 

Plotting these two lines together helps us diagnose our model:
* If training loss goes down but validation loss goes up, the model is **overfitting** (memorizing the training data).
* If both are going down, the model is still learning.
* If both have flattened out, the model has converged and stopped learning.

In [39]:
# Use the validation
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))

# Step 2: Compile
model.compile(loss='mse' , metrics = ['mae'] , optimizer = Adam(learning_rate= 0.01))

# Step 3: Fit
history = model.fit(X_train_scaled, y_train,
                     validation_data=(X_val_scaled, y_val),
                     epochs=50,
                     batch_size=64)

NameError: name 'Adam' is not defined

In [ ]:
# Model Weights
model.weights

In [ ]:
# Model Summary
model.summary()

In [ ]:
# Create a History Data Frame
history_df = pd.DataFrame(history.history)
history_df

In [ ]:
# Visualize Epochs vs. Loss for the Training Loss and Validation Loss
history_df.plot()
plt.xlabel('epochs')
plt.ylabel('loss');

## 12. Early Stopping (callback)

- Prevent overfitting
- will not waste the computing power
- save time
  
It is hard to guess exactly how many epochs a model needs. If you train for too few epochs, the model underfits. If you train for too many, it overfits. 

An **Early Stopping Callback** acts as an automatic brake. It monitors the validation loss and automatically stops training once the validation score stops improving, even if you haven't reached your maximum number of epochs. It can also automatically restore the model's best weights!

In [ ]:
# configure EarlyStopping parameters
es = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [ ]:
# Use the validation
# Step 1: Define
model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))

# Step 2: Compile
model.compile(loss='mse' , metrics = ['mae'] , optimizer = Adam(learning_rate= 0.01))

# Step 3: Fit
history = model.fit(X_train_scaled, y_train,
                     validation_data=(X_val_scaled, y_val),
                     epochs=100,
                     batch_size=64,
                     callbacks=[es])

In [ ]:
# Model Weights
model.weights

In [ ]:
# Model Summary
model.summary()

In [ ]:
# Create a History Data Frame
history_df = pd.DataFrame(history.history)
history_df

In [ ]:
# Visualize Epochs vs. Loss for the Training Loss and Validation Loss
history_df.plot()
plt.xlabel('epochs')
plt.ylabel('loss');

## 13.Multi-Feature Neural Network

In [ ]:
# configure EarlyStopping parameters
es = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Use ALL the numeric features this time, not just sq__ft
X = housing[['beds', 'baths', 'sq__ft', 'latitude', 'longitude']]
y = housing['price']

# Split into Train / Validation / Test again with the new feature set
X_train_all, X_test, y_train_all, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_all, y_train_all, test_size=0.20, random_state=42)

# Scale the (now multi-column) features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Use the validation
# Step 1: Define
model = Sequential([
    Input(shape=(5,)),                     # 5 features now
    Dense(20, activation='relu'),
    Dense(15, activation='relu'),
    Dense(1, activation='linear')
])

# Step 2: Compile
model.compile(loss='mae')

# Step 3: Fit
history = model.fit(X_train_scaled, y_train,
                     validation_data=(X_val_scaled, y_val),
                     epochs=100,
                     batch_size=64,
                     callbacks=[es])

In [ ]:
# Model Weights
model.weights

In [ ]:
# Model Summary
model.summary()

In [ ]:
# Create a History Data Frame
history_df = pd.DataFrame(history.history)
history_df

In [ ]:
# Visualize Epochs vs. Loss for the Training Loss and Validation Loss
history_df.plot()
plt.xlabel('epochs')
plt.ylabel('loss');